-- Italian names for the canonical ingredient vocabulary. The app shows
-- grocery lines in the user's interface language; EN/FR/ES existed since
-- 0002, Italian completes the set (fallback in the app is name_en for any
-- row this misses).

alter table canonical_ingredients add column name_it text;

update canonical_ingredients c set name_it = v.name_it
from (values
  ('abricot', 'albicocca'),
  ('abricot-sec', 'albicocca secca'),
  ('agneau', 'agnello'),
  ('ail', 'aglio'),
  ('amande', 'mandorle'),
  ('ananas', 'ananas'),
  ('artichaut', 'carciofo'),
  ('asperge', 'asparagi'),
  ('aubergine', 'melanzana'),
  ('avocat', 'avocado'),
  ('baguette', 'baguette (pane bianco)'),
  ('banane', 'banana'),
  ('basilic', 'basilico'),
  ('betterave', 'barbabietola'),
  ('beurre', 'burro'),
  ('boeuf-hache', 'carne macinata di manzo'),
  ('boeuf-steak', 'bistecca di manzo'),
  ('bouillon-cube', 'dado da brodo'),
  ('boulgour', 'bulgur'),
  ('brie', 'Brie'),
  ('brocoli', 'broccoli'),
  ('cabillaud', 'merluzzo'),
  ('cacahuete', 'arachidi'),
  ('camembert', 'Camembert'),
  ('canard', 'anatra'),
  ('cannelle', 'cannella'),
  ('capres', 'capperi'),
  ('carotte', 'carota'),
  ('celeri-branche', 'sedano'),
  ('celeri-rave', 'sedano rapa'),
  ('cerise', 'ciliegia'),
  ('champignon-de-paris', 'champignon'),
  ('chevre', 'formaggio di capra'),
  ('chocolat-noir', 'cioccolato fondente'),
  ('chorizo', 'chorizo'),
  ('chou-blanc', 'cavolo cappuccio'),
  ('chou-de-bruxelles', 'cavolino di Bruxelles'),
  ('chou-fleur', 'cavolfiore'),
  ('chou-kale', 'cavolo riccio (kale)'),
  ('ciboulette', 'erba cipollina'),
  ('citron', 'limone'),
  ('citron-vert', 'lime'),
  ('clementine', 'clementina'),
  ('comte', 'Comté'),
  ('concentre-tomate', 'concentrato di pomodoro'),
  ('concombre', 'cetriolo'),
  ('confiture', 'marmellata'),
  ('coriandre', 'coriandolo'),
  ('cornichons', 'cetriolini sottaceto'),
  ('courge-butternut', 'zucca butternut'),
  ('courgette', 'zucchina'),
  ('creme-fraiche', 'crème fraîche (panna acida)'),
  ('creme-liquide', 'panna da cucina'),
  ('crevette', 'gambero'),
  ('cumin', 'cumino'),
  ('curcuma', 'curcuma'),
  ('curry-poudre', 'curry in polvere'),
  ('dinde', 'tacchino'),
  ('dorade', 'orata'),
  ('echalote', 'scalogno'),
  ('emmental', 'Emmental'),
  ('endive', 'indivia belga'),
  ('epinard', 'spinaci'),
  ('farine-ble', 'farina di grano'),
  ('fenouil', 'finocchio'),
  ('feta', 'feta'),
  ('figue', 'fico'),
  ('flageolet', 'fagioli flageolet'),
  ('flocons-avoine', 'fiocchi d''avena'),
  ('fraise', 'fragola'),
  ('framboise', 'lampone'),
  ('fromage-blanc', 'formaggio fresco (fromage blanc)'),
  ('gingembre', 'zenzero'),
  ('haricot-blanc', 'fagioli bianchi'),
  ('haricot-rouge', 'fagioli rossi'),
  ('haricot-vert', 'fagiolino'),
  ('herbes-provence', 'erbe di Provenza'),
  ('huile-olive', 'olio d''oliva'),
  ('huile-tournesol', 'olio di girasole'),
  ('jambon-blanc', 'prosciutto cotto'),
  ('ketchup', 'ketchup'),
  ('kiwi', 'kiwi'),
  ('lait', 'latte'),
  ('lait-coco', 'latte di cocco'),
  ('lait-sans-lactose', 'latte senza lattosio'),
  ('laitue', 'lattuga'),
  ('lardons', 'pancetta a cubetti'),
  ('laurier', 'alloro'),
  ('lentille-corail', 'lenticchie rosse'),
  ('lentille-verte', 'lenticchie verdi'),
  ('mache', 'valeriana (songino)'),
  ('mais-doux', 'mais dolce'),
  ('mangue', 'mango'),
  ('mayonnaise', 'maionese'),
  ('melon', 'melone'),
  ('menthe', 'menta'),
  ('miel', 'miele'),
  ('moule', 'cozza'),
  ('moutarde', 'senape'),
  ('mozzarella', 'mozzarella'),
  ('myrtille', 'mirtillo'),
  ('navet', 'rapa'),
  ('nectarine', 'nettarina'),
  ('noisette', 'nocciole'),
  ('noix', 'noci'),
  ('noix-cajou', 'anacardi'),
  ('oeuf', 'uovo'),
  ('oignon', 'cipolla'),
  ('oignon-nouveau', 'cipollotto'),
  ('oignon-rouge', 'cipolla rossa'),
  ('olives', 'olive'),
  ('orange', 'arancia'),
  ('pain-complet', 'pane integrale'),
  ('pain-de-mie', 'pancarré'),
  ('pain-epeautre-levain', 'pane di farro a lievitazione naturale'),
  ('panais', 'pastinaca'),
  ('paprika', 'paprika'),
  ('parmesan', 'parmigiano'),
  ('pasteque', 'anguria'),
  ('patate-douce', 'patata dolce'),
  ('pates-ble', 'pasta di grano'),
  ('peche', 'pesca'),
  ('persil', 'prezzemolo'),
  ('petit-pois', 'piselli'),
  ('pistache', 'pistacchi'),
  ('pleurote', 'funghi pleurotus'),
  ('poire', 'pera'),
  ('poireau', 'porro'),
  ('pois-chiche', 'ceci'),
  ('poivre', 'pepe nero'),
  ('poivron-rouge', 'peperone rosso'),
  ('poivron-vert', 'peperone verde'),
  ('polenta', 'polenta'),
  ('pomme', 'mela'),
  ('pomme-de-terre', 'patata'),
  ('porc', 'maiale'),
  ('potimarron', 'zucca hokkaido'),
  ('poulet', 'pollo'),
  ('prune', 'prugna'),
  ('quinoa', 'quinoa'),
  ('radis', 'ravanello'),
  ('raisin', 'uva'),
  ('raisin-sec', 'uvetta'),
  ('ricotta', 'ricotta'),
  ('riz', 'riso bianco'),
  ('romarin', 'rosmarino'),
  ('roquette', 'rucola'),
  ('sardine', 'sardina'),
  ('sarrasin', 'grano saraceno'),
  ('sauce-soja', 'salsa di soia'),
  ('sauce-tomate', 'passata di pomodoro'),
  ('saucisse', 'salsiccia'),
  ('saumon', 'salmone'),
  ('sel', 'sale'),
  ('semoule-couscous', 'cuscus (semola di grano)'),
  ('sirop-erable', 'sciroppo d''acero'),
  ('sucre', 'zucchero bianco'),
  ('thon-boite', 'tonno in scatola'),
  ('thon-frais', 'tonno fresco'),
  ('thym', 'timo'),
  ('tofu-ferme', 'tofu compatto'),
  ('tomate', 'pomodoro'),
  ('truite', 'trota'),
  ('veau', 'vitello'),
  ('vin-blanc', 'vino bianco secco'),
  ('vin-rouge', 'vino rosso'),
  ('vinaigre-balsamique', 'aceto balsamico'),
  ('vinaigre-vin', 'aceto di vino'),
  ('yaourt-nature', 'yogurt bianco')
) as v(slug, name_it)
where c.slug = v.slug;
